USE kpopnation;
INSERT INTO customer VALUES (1,"mattjone5","$2y$10$bBISP7494VIqUmfXT8yq2OnSLwqIti1Jk4BwdQL3dSAdNJX2yv4B6","Matt","Jones","2001-05-27","fakeemail@test.org");
INSERT INTO customer VALUES (2,"test","$2y$10$bBISP7494VIqUmfXT8yq2OnSLwqIti1Jk4BwdQL3dSAdNJX2yv4B6","Okita","Souji","1840-01-01","fakeemail@test.org");
INSERT INTO customer VALUES (3, "bsmith","$2y$10$MIIjSYnPf4eLTK4P2HZhgessRUR8ClqO7WFQW2voOEGgTxHkKUMs2","Tamamo","Mae", "100-01-01","okbuddy@hottakes.org");
INSERT INTO customer VALUES (4, "pjones","$2y$10$wqJUMtkNgE04KlPe7sWXK.kp6RLbB0YozJDRiKwkuaLcxNJFSxlIy", "Jeanne","Darc",	"1412-01-01", "iguess@ok.gov");


INSERT INTO admin VALUES (1,"mattjone5");

INSERT INTO news VALUES (1, "bts","BTS Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");
INSERT INTO news VALUES (2, "bts","BTS Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");
INSERT INTO news VALUES (3, "bts","BTS Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");
INSERT INTO news VALUES (4, "bts","BTS Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (5, "blackpink","BlackPink Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (6, "blackpink","BlackPink Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (7, "blackpink","BlackPink Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (8, "blackpink","BlackPink Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (9, "ioi","I.O.I Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (10, "ioi","I.O.I Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (11, "ioi","I.O.I Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (12, "ioi","I.O.I Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (13, "itzy","ITZY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (14, "itzy","ITZY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (15, "itzy","ITZY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (16, "itzy","ITZY Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (17, "ntchollywood","NTC HollyWood Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (18, "ntchollywood","NTC HollyWood Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (19, "ntchollywood","NTC HollyWood Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (20, "ntchollywood","NTC HollyWood Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (21, "nmixx","nmixx Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (22, "nmixx","nmixx Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (23, "nmixx","nmixx Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (24, "nmixx","nmixx Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (25, "traineea","Trainee A Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (26, "traineea","Trainee A Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (27, "traineea","Trainee A Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (28, "traineea","Trainee A Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (29, "younite","Younite Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (30, "younite","Younite Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (31, "younite","Younite Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");

INSERT INTO news VALUES (32, "younite","Younite Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus sodales est. Maecenas enim tortor, luctus id commodo in, iaculis porta nunc. Aenean ut vulputate erat, nec consequat ex. Donec elementum, metus et maximus scelerisque, nunc ante dapibus massa, eget pulvinar lorem turpis ut mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam ac ante porta rutrum. Sed pharetra consectetur ex sit amet dictum. Etiam sed dictum ipsum.

Sed gravida leo id auctor ultricies. Nulla semper ex sapien, nec feugiat tortor pellentesque at. Nullam varius ut augue non posuere. Duis at nisl a tellus tempor pharetra quis at erat. Nunc sagittis sem vel vulputate maximus. Nulla facilisis hendrerit sapien, in consequat velit efficitur id. Curabitur venenatis diam condimentum enim maximus lacinia. In pellentesque mattis suscipit. Sed nec odio arcu. Nam auctor sit amet ipsum a vulputate. Curabitur pretium est nec ligula blandit fermentum. Aenean pellentesque ex non lacus elementum, sed imperdiet justo hendrerit.

Vivamus pharetra facilisis finibus. Nullam consequat pellentesque molestie. Donec eget condimentum eros. Aliquam id mi sit amet felis imperdiet lacinia nec a nisi. Nulla tempor ipsum nec vehicula maximus. Vivamus sollicitudin auctor ligula, vel mollis nunc tincidunt mattis. Morbi congue et ligula quis gravida. Aenean mattis elit quis volutpat efficitur. Vivamus malesuada eu leo id sodales. Curabitur venenatis est neque, ut faucibus ex sodales eget. Vestibulum rutrum mi quis urna blandit sollicitudin. Integer id dictum nulla. Cras mauris nulla, fermentum eget bibendum ut, semper a leo.

Vivamus nec turpis sit amet mauris dictum posuere id at ligula. Pellentesque non nisi in arcu cursus fringilla. In non malesuada nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus condimentum placerat lorem, id ullamcorper leo cursus vitae. In vel ex ultricies, mollis turpis at, lacinia elit. Phasellus sed augue fermentum, bibendum orci eu, laoreet magna. Mauris non sodales leo. In ac risus metus. Nam in ex interdum, rutrum erat vel, condimentum ante. Cras vitae massa ut diam tincidunt iaculis.

Praesent porta sem in rutrum bibendum. Donec gravida, nunc porta blandit dapibus, eros ligula bibendum justo, sed elementum dui libero quis nisl. Nullam blandit enim sed purus fermentum, eget tincidunt metus tempus. Integer sit amet tellus ante. Duis eros magna, rutrum eget nibh vitae, pharetra consequat nisl. Nullam eget rutrum velit, eu pharetra elit. Aliquam facilisis malesuada dolor non imperdiet. Suspendisse a metus ante. Sed in cursus tellus. Duis id eros ultricies, tincidunt enim non, fringilla lorem. Nam posuere aliquet tortor non vulputate. Proin accumsan interdum tortor, at aliquet nulla luctus eu. Quisque eleifend tincidunt bibendum.");



INSERT INTO groupsfollowing VALUES (1, "1","0","0","0","0","0","0","0");
INSERT INTO groupsfollowing VALUES (2, "0","0","0","0","0","0","0","0");
INSERT INTO groupsfollowing VALUES (3, "0","0","0","0","0","0","0","0");
INSERT INTO groupsfollowing VALUES (4, "0","0","0","0","0","0","0","0");